### ISSUE TITLE
Teste do projeto de pagamentos

### ISSUE THREAD

**Issue by G-Nozawa** [Team-Dire/Sistema-agendamento-clinico#11]

**Comment by GuiCT** [comment]
# Defeitos na Fase de Projeto: Segundo Sprint

## Diagrama de Classes
| Defeito | Requisito | Classe |                                                                                Descrição                                                                                |
|:-------:|:---------:|:------:|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|    -    |     -     |    -   |                                           Não apresentou nenhum defeito                                           |
