### ISSUE TITLE
Teste da implementação do pagamento

### ISSUE THREAD

**Issue by G-Nozawa** [Team-Dire/Sistema-agendamento-clinico#13]

**Comment by GuiCT** [comment]
@GuiBatalhoti 

Algumas coisas que eu percebi que podem ser melhoradas, não necessariamente sendo defeitos:
No momento de cadastrar uma nova consulta, o formato de data utilizado é d/m/YY, acho que seria mais proveitoso usar o padrão dd/mm/YY ou dd/mm/YYYY, que é o padrão para a nossa região.

Na hora de pagar a consulta, ao selecionar o tipo de pagamento particular, a TextBox reservada para inserir o nome do convênio é desabilitada, mas não fica cinza, se for possível mudar isso, acho que seria importante para o quesito visual.

Esse mesmo comportamento citado no item anterior ocorre na hora de criar usuário, com a TextBox ficando disponível apenas quando a opção "Médico" está selecionada, mas não ficando cinza.
