### ISSUE TITLE
Teste da análise das férias e encaixe

### ISSUE THREAD

**Issue by G-Nozawa** [Team-Dire/Sistema-agendamento-clinico#15]

**Comment by GuiCT** [comment]
# Defeitos na Fase de Análise: Férias e Encaixes
## Diagrama de Casos de Uso
O Diagrama de Casos de Uso não foi atualizado para incluir os casos de uso incrementado no Sprint 3.

## Modelo Conceitual

| Defeito | Classe |                                                               Descrição                                                              |
|:-------:|:------:|:------------------------------------------------------------------------------------------------------------------------------------:|
|    1    |   O   | Conceito "Secretário" não tem associação direta com conceito "Férias", sendo que o secretário é o responsável pelo agendamento das férias. |
|    2    |   O   | Conceito "Secretário" não tem associação de "adiar" com conceito "Consulta". |
|    3    |   O   | Conceito "Secretário" não tem associação de "registrar" com conceito "Consulta". |
|    4    |   O   | Conceito "Secretário" não tem associação de "encaixar" com conceito "Consulta". |

**Comment by becelli** [comment]
Atualizado e ajustado de acordo com os defeitos apontados

**Comment by GuiCT** [comment]
Tudo OK. Esperando merge.
