### ISSUE TITLE
Análise de agendas

### ISSUE THREAD

**Issue by G-Nozawa** [Team-Dire/Sistema-agendamento-clinico#2]
Esse sprint visa implementar os casos de uso dos requisitos 1-9 do documento de requisitos. Em suma, nessa issue serão criadas os casos de usos para agendamento de consultas, associação de médicos aos secretários, cancelamento de  consultas e sistema de autenticação do usuário.

**Comment by GuiCT** [comment]
# Defeitos na Fase de Análise: RF1 - RF9

## Documento de requisitos
| Defeito | Requisito | Classe |                                                                                Descrição                                                                                |
|:-------:|:---------:|:------:|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|    1    |     1     |    O   |                                           Falta explicitar quais informações devem ser guardadas para médicos ou secretários.                                           |
|    2    |     4     |   FE   | O documento de requisitos não deve apresentar forma com que uma notificação é feita, apenas que ela é feita. Não é necessário especificar que é uma notificação pop-up. |

## Casos de Uso
Para o caso de uso "Autenticar um usuário":
| Defeito | Classe |                                                                                                                            Descrição                                                                                                                            |
|:-------:|:------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|    1    |   FE   | O documento de requisitos pede para que o sistema seja capaz de fazer autenticação, mas em nenhum momento cita que isso será feito a partir de login com usuário e senha. Trata-se, portanto, de "como fazer" e não "o que fazer", não sendo papel do analista. |

Para o caso de uso "Adicionar um novo usuário ao software":
| Defeito | Classe |                                                               Descrição                                                              |
|:-------:|:------:|:------------------------------------------------------------------------------------------------------------------------------------:|
|    -    |    -   | Erro reminiscente do caso de uso anterior: em nenhum momento foi dito no Documento de Requisitos que há processo de login envolvido. |
| -       | -      | Erro reminiscente do Documento de Requisitos: não são apresentadas as informações associadas a um usuário do software.               |

**Comment by becelli** [comment]
Elementos corrigidos. Por gentileza, poderia reavaliar os itens mencionados no caso de uso?

**Comment by GuiCT** [comment]
Falta só especificar as informações adicionadas pelo novo RF: "R.1.1 Os sistema deverá armazenar os dados de CPF, senha, nome do usuário, e caso o usuário seja um médico, especialização do médico. (E)", aí fica ok
