### ISSUE TITLE
Teste da análise

### ISSUE THREAD

**Issue by G-Nozawa** [Team-Dire/Sistema-agendamento-clinico#3]
Esse issue visa realizar o teste dos casos de uso criados para os requisitos 1-9 do documento de requisitos.

**Comment by GuiCT** [comment]
Os defeitos encontrados na análise foram apontados diretamente na issue da mesma, isto é: https://github.com/Team-Dire/Sistema-agendamento-clinico/issues/2#issuecomment-1317852285

Uma errata a se fazer: o caso de uso de "Cancelar consulta" foi escrito de forma duplicada, não percebi no momento e esqueci de apontar esse defeito.
