### ISSUE TITLE
Projeto de agendas

### ISSUE THREAD

**Issue by G-Nozawa** [Team-Dire/Sistema-agendamento-clinico#4]
Essa issue tem o objetivo de criar os diagramas de comunicação e de classes baseados nos casos de usos gerados para os requisitos 1-9.

**Comment by Salies** [comment]
Projeto de agendas (R1-9) finalizado. Branch com pull request criada. Aguardando SQA.
https://github.com/Team-Dire/Sistema-agendamento-clinico/tree/projeto-sprint-1
