### ISSUE TITLE
Teste do projeto

### ISSUE THREAD

**Issue by G-Nozawa** [Team-Dire/Sistema-agendamento-clinico#5]

**Comment by GuiCT** [comment]
Percebi apenas 2 defeitos no Diagrama de Classes, que se corrigidos podem melhorar a legibilidade do mesmo. Utilizei de print e anotação para facilitar o entendimento:

Substituição de atributo por relação de agregação/composição. Lembrar que agregação pressupõe que a parte pode existir sem o todo e a composição pressupõe que a parte NÃO pode existir sem o todo.

![agregacaocomposicao](https://user-images.githubusercontent.com/55140084/204157911-729e97e7-949b-47e7-a72f-92f7093d7ba4.png)

Não necessidade de incluir os construtores das classes.

![construtores](https://user-images.githubusercontent.com/55140084/204157915-d06a19f1-403c-4e66-9e56-f7fa9e138347.png)

Essas são direcionadas para @Salies .

Para @becelli , Daniel apontou um detalhe importante de considerar: não há forma unívoca de identificar um determinado paciente, o que pode causar problemas no futuro, é algo a se considerar.

**Comment by Salies** [comment]
Defeitos corrigidos. Os arquivos corretos já estão na brach.

**Comment by GuiCT** [comment]
Você fez a associação entre Secretario e Medico, mas faltou indicar que se trata de uma agregação/composição. Fora isso tudo está correto.

**Comment by GuiCT** [comment]
ERRATA: não era necessário fazer uma agregação/composição, mas uma simples associação, agora está tudo certo.
