### ISSUE TITLE
Teste da implementação das agendas

### ISSUE THREAD

**Issue by G-Nozawa** [Team-Dire/Sistema-agendamento-clinico#7]

**Comment by GuiCT** [comment]
Estou um pouco atrasado nessa revisão, mas a parte boa é que não encontrei nenhum defeito problemático.

Só algumas sugestões @GuiBatalhoti :
- Deixar o nome do "package" estritamente igual ao nome da pasta que contém os arquivos desse package. No Netbeans isso não deve ocasionar em nenhum problema, mas quando abri o projeto no IntelliJ IDEA Community, tive problemas para usar os arquivos dentro do package "user", ao renomear o package para "User", não tive mais nenhum problema.
- Não é necessário criar uma pasta para cada classe do diagrama de classes, imagino que seria mais vantajoso colocar a maioria dos arquivos em um package chamado "model" para facilitar a navegação. Isso será mais relevante quando o projeto estiver avançado.

E algumas coisas que fiquei em dúvida:
- Não sei se é muito "correto" implementar muita lógica nos arquivos referentes à Interface. Algumas verificações podem ser feitas, mas não sei em que ponto isso deixa de ser uma boa prática.
