### ISSUE TITLE
Teste da análise de pagamentos

### ISSUE THREAD

**Issue by G-Nozawa** [Team-Dire/Sistema-agendamento-clinico#9]

**Comment by GuiCT** [comment]
# Defeitos na Fase de Análise: RF10 - RF12

## Casos de Uso
Para o caso de uso "Verificar a lista de pacientes de um médico":
| Defeito | Classe |                                                                                                                            Descrição                                                                                                                            |
|:-------:|:------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|    1    |   FE   | Não é necessário incluir a ação "O secretário executa o software.". |

Para o caso de uso "Receber o pagamento de uma consulta":
| Defeito | Classe |                                                               Descrição                                                              |
|:-------:|:------:|:------------------------------------------------------------------------------------------------------------------------------------:|
|    1    |   FE   | Não é necessário incluir a ação "O secretário executa o software.". |

## Modelo Conceitual

| Defeito | Classe |                                                               Descrição                                                              |
|:-------:|:------:|:------------------------------------------------------------------------------------------------------------------------------------:|
|    1    |   O   | O conceito de pagamento não aparece em nenhum momento no Modelo Conceitual |
|    2    |   O   | Não existe associação direta entre "Médico" e "Paciente" |
